### ISSUE TITLE
Bug: When editing a press release, I can't save my edit (error message: pretty URL is already existing)

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1054]
When logged into Admin role, I am finding this bug on dev, where I can't save changes to an existing press release. This does not happen when logged in as editor or author.

How to reproduce:

1. Edit a press release.  
2. Add some content to one of the fields
3. Go to the bottom, and save the edit

You will get this screen: 
![image](https://user-images.githubusercontent.com/31222859/54373310-67402e00-4653-11e9-8a52-49ea9a8d22ec.png)

**Comment by adriancofie** [comment]
@VictoriaSunNIH  
The error message is actually correct. This isn't an issue with site sections, its an issue with the  default YML content for Press Releases.  

There are multiple nodes loaded into the system that have the same site section and pretty URL.  Our validation disallows that, hence the message.

**Comment by bgnih** [comment]
Caused by duplicate node being added in both `013_press_release_chemotherapy.content.yml` and `press_release.content.yml`.  Removed from `press_release.content.yml`.

Note: This was allowed by a lack of validation on yaml_content imports.   We should add an 
```
$violations = $entity->validate();
// process violations here
```
to the ENTITY_PRE_SAVE event in cgov_yaml_content module (or patch the yaml_content module to do it).

**Comment by bgnih** [comment]
Added ticket #1111 to backlog to prevent in future.
