### ISSUE TITLE
Allow media types to be added to Lists and Related Resources

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1145]
Currently, we are only able to add internal and external links to Lists, Cancer Type Guide Card More Information, Cancer Research List Pages, and Related Resources. We need to be able to add:
* files
* videos
* infographics 

They should appear as regular links

**Comment by BrendanBeltzNIH** [comment]
Part of this story requires creating a new, single agnostic media type paragraph for the media types (since the related resources field handles paragraphs). The paragraph would need an entity reference field that would use a media browser constrained to the appropriate media types. The field itself would need to be rendered in such a way that only the aliased path and label/name/title were made available.

Bryan has created a model here https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-Media-Link.
