### ISSUE TITLE
Alias for files should take you directly to the download

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1166]
When clicking on the file alias in drupal, users should be taken directly to the download.

The view for it /media/ID should also take users to the download

**Comment by bryanpizzillo** [comment]
As usual, this is another requirement that Drupal will have issues with OOB. OOB there is no download route. Rough approach:
1. Take the guts of the controller from https://www.drupal.org/project/media_entity_download. That explains (ish) how to stream the file back to the client from a controller.
2. Replace the core.media.canonical controller, but only for files.
    * We could do a route subscriber, replace the media controller with our own that inherits from media controller. If file, do our stuff, else parent::handle
    * We could do a EventSubscriber listening to the request event, and just stream the file back to the client.

I think the second option for #2 above is probably the best because in the request callback you will have the media item loaded for you and you can set the response right there.

Oh also make sure that the robots HTTP header is there when the files are marked as do not index.
