### ISSUE TITLE
Drop revision table from press_release_rss view

### ISSUE THREAD

**Issue by bgnih** [NCIOCPL/cgov-digital-platform#1198]
If an English Press Release node has a Spanish translation with a different Posted_Date value, a duplicate record appears in the English Press Release feed.

Followup on #298.

**Comment by bkline** [comment]
I'm going to dig in on my local machine, but I was taking a preliminary look on www-dev-ac.cancer.gov, and ran into a 404 for http://www-dev-ac.cancer.gov/admin/structure/views/view/press_release_rss (logged in as admin).

**Comment by bkline** [comment]
I am able to duplicate the behavior described above on my own instance built from the current `develop` branch. I have modified `field_date_posted` for node 76 (_Press Release 3_ and _Press Release 3 - ES_, loaded from a `yaml` sample content file), setting the English translation's copy of that field to 2019-01-03 and the Spanish translation's value for that field as 2019-01-05, with the latest revision set to `published` for both languages. Both translations shows up in the English RSS feed.

The SQL for the feed's view (reformatted to avoid the need for scrolling) is

```sql
SELECT DISTINCT node__field_date_posted.field_date_posted_value
             AS node__field_date_posted_field_date_posted_value,
                node_field_data.nid AS nid
FROM {node_field_data} node_field_data
INNER JOIN {node_field_revision} node_field_revision
        ON node_field_data.vid = node_field_revision.vid
LEFT JOIN {node__field_date_posted} node__field_date_posted
       ON node_field_data.nid = node__field_date_posted.entity_id
      AND (node__field_date_posted.deleted = '0'
      AND node__field_date_posted.langcode = node_field_data.langcode)
WHERE (node_field_data.status = '1')
  AND (node_field_data.type IN ('cgov_press_release'))
  AND (node_field_revision.langcode IN ('en'))
ORDER BY node__field_date_posted_field_date_posted_value DESC
LIMIT 10 OFFSET 0
```
You can see that `langcode` is constrained to be `'en'` for the `node_field_revision` table. You can also see that the join to pick up rows from the `node__field_date_posted` table ensures that `langcode` in that table matches the `langcode` in the `node_field_data` table. But there is nothing in the query which makes sure that `langcode` in `node_field_revision` matches `langcode` in either of the other two tables.

So this row is the only one pulled from the `node_field_revision` table for this node:

```sql
MariaDB [drupal]> select langcode, status, title
    -> from node_field_revision where vid = 325
    -> and langcode in ('en');
+----------+--------+-----------------+
| langcode | status | title           |
+----------+--------+-----------------+
| en       |      1 | Press Release 3 |
+----------+--------+-----------------+
1 row in set (0.00 sec)
```

But it gets joined to both of these rows in `node_field_data`:

```sql
MariaDB [drupal]> select vid, langcode, status, title
    -> from node_field_data where nid = 76;
+-----+----------+--------+----------------------+
| vid | langcode | status | title                |
+-----+----------+--------+----------------------+
| 325 | en       |      1 | Press Release 3      |
| 325 | es       |      1 | Press Release 3 - ES |
+-----+----------+--------+----------------------+
2 rows in set (0.00 sec)
```

... which in turn get joined to these two rows (respectively) in `node__field_date_posted`:

```sql
MariaDB [drupal]> select deleted, revision_id, langcode, field_date_posted_value
    ->  from node__field_date_posted where entity_id = 76;
+---------+-------------+----------+-------------------------+
| deleted | revision_id | langcode | field_date_posted_value |
+---------+-------------+----------+-------------------------+
|       0 |         325 | en       | 2019-01-03              |
|       0 |         325 | es       | 2018-01-05              |
+---------+-------------+----------+-------------------------+
2 rows in set (0.00 sec)
```

Because the posted dates are different, the `DISTINCT` keyword isn't able to reduce the number of rows to 1. So it looks like we might have another bug in core (though I haven't been able to find a bug report for it). I assume we don't have time at this point in the schedule to deal with tracking down where it's happening in the `view` module and getting a patch to them (only to have them tell us they don't want it, very likely). So I'll see if I can create a hook that fixes the query.

**Comment by bkline** [comment]
Bringing the revision table into the filter caused the duplicates, and was a mistake. Removing the use of the revision table from the fields list as well.
