### ISSUE TITLE
Workflow: control when content may be deleted

### ISSUE THREAD

**Issue by bkline** [NCIOCPL/cgov-digital-platform#121]
According to https://github.com/NCIOCPL/cgov-digital-platform/wiki/Editorial-Workflow a content item can only be deleted by an author if it has never been published. Make it so, using a `hook_node_access` implementation.

**Comment by bkline** [comment]
My proposed approach will determine whether the current user is an "author" for the purposes of this ticket if she does not have the `use editorial_workflow transition publish` permission. (Another option would be to check whether the account has the `content_editor` role, but determining what a user is allowed to do by directly looking at roles is frowned upon). Also, this approach will examine the `node_field_revision` table directly to see if any revision for the node has a `status` column with the value of 1. This is because the `AccountInterface` API only has a method for determining whether the node is currently published (`isPublished()`), not a method for determining whether the node has _ever_ been published.

**Comment by bgnih** [comment]
@bkline If I am reading this properly, this would allow `Content Editors` to delete ever-published content.   It looks like the [specs](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Editorial-Workflow) say only `Advanced Editors` should be able to permanently delete content.  

As a more general question, would it be better to create a new permissions `delete previously-published content` or `delete previously-published pony content` (or whatever) and assign that permission to the appropriate role, rather than inferring the right from the allowed workflow transitions?  (I'm not sure which method would be the best practice, but having a permission seems more self-documenting within the system).
