### ISSUE TITLE
Add a helper function to attach content types to workflow

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#127]

**Comment by bkline** [comment]
Here's my proposed approach for this ticket. I'm going to assume, based on its name, that [`Drupal\cgov_core\CgovCoreTools`](https://github.com/NCIOCPL/cgov-digital-platform/blob/develop/docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/CgovCoreTools.php) is the class in which we would want to implement this functionality. Instead of a single "helper function" I suggest that we create two methods, one for attaching a named content type to a named workflow, and another for assigning a named permission to a named role. As an example of the code for the former, something like:

```
  /**
   * .... assumes we have been constructed with a `$this->container`, and that
   * the only bundle we're using for our content types is `node`.
   */
  public function attachContentTypeToWorkflow($type_name, $workflow_name) {
    $entityTypeManager = $this->container->get('entity_type.manager');
    $workflows = $entityTypeManager->getStorage('workflow')->loadMultiple();
    $workflow = $workflows[$workflow_name];
    $workflow->getTypePlugin()->addEntityTypeAndBundle('node', $type_name);
    $workflow->save(TRUE);
  }
```

**Comment by bgnih** [comment]
There's a addRolePermissions() method in PR #260 that will add the permissions to role(s).  See https://github.com/NCIOCPL/cgov-digital-platform/pull/260/files#diff-dd38af5461bbb4b3805f13398351810a for example usage.

**Comment by bkline** [comment]
So that half of this ticket is redundant? Shall I modify the title and description to limit it to the first method (which I've sort of pseudo-coded above)?

**Comment by bgnih** [comment]
Yes, please.  Perms are in #124 and #126 already.

**Comment by bkline** [comment]
Title modified. I'll take a stab at the implementation, if that's ok with you. Proposed approach look about right?
