### ISSUE TITLE
Create blog admin role

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1312]
We would like to have a new blog admin role called "Blog Manager".  This also requires a new blog series workflow - which should mimic the regular content edit/review/publish workflow

This role would only be allowed to edit, review and publish blog series.

**Comment by daquinohd** [comment]
@lburack @VictoriaSunNIH - this is ready for testing on http://ncigovcdode109.prod.acquia-sites.com. 

The blog_manager role has the following permissions for Blog Series only:
* Translate content
* Create content
* Delete content
* Edit content
* Revert revisions
* View revisions

The Blog Workflow has the same states as the Editorial Workflow: 
Draft, Review, Published, Editing, Post-Publication Review, Archive Requested, Archived

**Comment by lburack** [comment]
@daquinohd – there's no Moderated Content tab. I created a blog series and moved it to Review, but now I can't find it because it hasn't been published yet. I tried changing the Published Status filter to search for Unpublished content, but that still doesn't serve up my unpublished blog. 

Also, I'm not able to translate a blog series. I tried to translate the RAS Dialogue Blog (only an English version exists on the ODE), but there's no dropdown option to Translate. 
<img width="1527" alt="Screen Shot 2019-04-25 at 8 32 58 PM" src="https://user-images.githubusercontent.com/29731392/56776264-5c6fd180-6799-11e9-8291-627a9b0c4512.png">
I edited the blog series and hit the Translate tab at the top, but there was no way to create a Spanish version.
<img width="420" alt="Screen Shot 2019-04-25 at 8 31 42 PM" src="https://user-images.githubusercontent.com/29731392/56776236-2d596000-6799-11e9-832e-b46fa08c358e.png">

I am able to edit the other blog series that have been created, adding content (particularly featured posts). I was also able to revert revisions.

**Comment by VictoriaSunNIH** [comment]
@daquinohd Adding to Lindsay's comment from above - I found where her translate option went...when I logged in as an editor, and then searched for the blog series in the content overview, I had an option to translate.  I think for editors, we should only allow them to view the series, but not have any options to edit, delete or translate.

![image](https://user-images.githubusercontent.com/31222859/56810252-d0df5a80-6803-11e9-8b77-902058ac0e4e.png)
