### ISSUE TITLE
Wrong main menu on “Subvenciones y capacitación” (Grants and training)

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1512]
1. Go to the English version of the site.
1. Click on "Grants & Training".
1. Click on the "Spanish" link.

* The main menu appears in English.
* The URL path is `/espanol/grants-training` instead of `/espanol/subvenciones-capacitacion`

**Comment by BrendanBeltzNIH** [comment]
Is this a bug? The issue is simple, whoever made the yaml content attached the english site section to the spanish translation as well. It's just a matter of switching what site section is used. 

![image](https://user-images.githubusercontent.com/34315527/56665181-8d57e580-6677-11e9-8038-f096c8e1e4df.png)

**Comment by VictoriaSunNIH** [comment]
YAML content issue.
