### ISSUE TITLE
At mobile breakpoint the Section Menu button on the top right corner gets hidden when expanded 

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#1536]
Steps to reproduce:
1. Go to http://www-dev-ac.cancer.gov/about-cancer/coping/feelings/relaxation
2.Switch to mobile breakpoint and then click the Section Menu button on the top right corner
3.See that the Section Menu button with the arrow pointing downwards does not appear when the items under the section menu is expanded

![image.png](https://images.zenhubusercontent.com/5c8fbb20b65bca7678bd0f3a/690d8db0-4e32-4ebb-a721-64744a893121)

**Comment by BrendanBeltzNIH** [comment]
This is because the ordering of rules related to breakpoints has changed in Common.css. 

Good: 
![image](https://user-images.githubusercontent.com/34315527/56673206-d9118b80-6685-11e9-9bf9-39790a70672d.png)

Bad:

![image](https://user-images.githubusercontent.com/34315527/56673229-e464b700-6685-11e9-96ac-8b7733e56571.png)

This needs to be tracked down and fixed in such a way as to not cause unintended side-effects.

**Comment by BrendanBeltzNIH** [comment]
This was repeated in #1766. Closing as duplicate.
