### ISSUE TITLE
Lead image on the Blog page and Press Release page has 3 <p> tags out of which only one is being used for image caption, other 2 are empty tags.

### ISSUE THREAD

**Issue by SupriyaSaxena0605** [NCIOCPL/cgov-digital-platform#1574]
http://www-dev-ac.cancer.gov/news-events/cancer-currents-blog/2019/vitamin-d-supplement-cancer-prevention

Lead image on the blog page has 3 "p" tags out of which only one is being used for image caption, other 2 are empty tags. Same is the case with Press Release page also(http://www-dev-ac.cancer.gov/news-events/press-releases/2018/leukemia-cll-ibrutinib-trial)
Is this expected?
![image](https://user-images.githubusercontent.com/31008800/56831081-364c3f00-6836-11e9-84d8-98645136136b.png)

**Comment by BrendanBeltzNIH** [comment]
This is just because the caption is wrapped in a p tag in the image macro for articleImage. Which is redundant because the field contents seem to be autowrapped in p tags (the yaml content for the field_caption doesn't include markup but is getting wrapped anyway on image entity creation).

The simplest fix is removing the P tags 
![image](https://user-images.githubusercontent.com/34315527/56973508-f8ebf800-6b3a-11e9-83d8-534772bb9e8e.png)

This is low priority as the p tags have no effect on visible layout or javascript operations.
