### ISSUE TITLE
Biography Title Template Update

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#1583]
On the Biography, the Full Name should be used for the H1 of the page, instead of building it up from the First Name/Last Name/etc. fields. This is what's done in percussion and needs to be done in Drupal for content to migrate over correctly for DCEG.

**Comment by sarinapadilla** [comment]
After looking in Percussion, the Long Title is used for the H1 of the page instead of building it up from the First Name/Last Name/etc. fields. We need to update the Drupal page template for Biography to use the Full Name field for the H1 instead of building it up. This also means we will leave the tooltip for Full Name as-is.
