### ISSUE TITLE
The body field of the content_block block_content entity should be constrained to full_html text format

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#1624]
The body field of the content_block block_content entity should be constrained to full_html text format.

Any existing YAML should be updated. There should not be any that I can think of. This is related to #1192.

**Comment by BrendanBeltzNIH** [comment]
#1623 and this are connected in the current implementation as both block types use the same default body field. The way we currently use our allowTextFormats tool, we can't constrain the same field in two different usages within one module. As best I can tell, at least. 

Perhaps instead of using body, a different field should have been used for one or both blocks to allow granular allowed types?
