### ISSUE TITLE
Content type references cleanup (low priority)

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#1637]
Some other (low priority) code cleanup that can occur:

remove if(location.pathname.match('espanol')) block from HomePage.js. No longer needed with Drupal platform
remove .cgvpressrelease hr.ps-divider from mainContent.scss. These `<hr>` elements are no longer present on press releases. These `<hr/>` elements no longer appear on press release pages.

Closing out #1197 with this + the broken out stories for specific content types.

**Comment by BrendanBeltzNIH** [comment]
I know it's just a cut and paste. But these two aren't related, and the first element is actually a different task that might need to be done in multiple places (investigation needed) and has nothing to do with the original investigation assignment of content specific class references. There's a whole different story to look through all the ways the front end is deriving things it no longer needs to, language and otherwise.

The second thing should have been in one of the broken out PRs already.

**Comment by BrendanBeltzNIH** [comment]
the location.pathname.match occurrences have already been removed.
