### ISSUE TITLE
Microsite Styling: Contact & Dictionary Icons should not show on mobile

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1641]
For all 3 themes (blue, purple and green), there is are no contact and dictionary links on desktop (this is correct), but on mobile, the contact and dictionary icons appear.

These should be hidden on mobile for these themes (and only show on cancer.gov)

**Comment by BrendanBeltzNIH** [comment]
The PR with #820 just went in. This creates the mobile nav and the search bar as blocks in distinct regions. Disabling these on a microsite is as simple as not putting any blocks there to begin with (I am currently creating theme with yaml content - but they otherwise do not automatically prepopulate). As a consequence, I'm not sure if this is a valid issue or should be closed.

**Comment by VictoriaSunNIH** [comment]
@BrendanBeltzNIH  - sounds like this won't be a valid issue then when we migrate the real content. Closing for now.
