### ISSUE TITLE
Build Data Structure for PDQ Cancer Info Summary

### ISSUE THREAD

**Issue by nicolecrom** [NCIOCPL/cgov-digital-platform#165]
Dependent on Issue #164

**Comment by blairlearn** [comment]
Approach:

1.  Create new content type `pdq_summary` via UI
1.1  No fields
1.1 Export config and add to `profiles/custom/cgov_core/modules/pdq_summary`
1.1 Create unit test (Can I create a node of this type?)
1. Create fields via UI
1.1 Export config
1.1 Create unit tests (Do these fields exist?)
1.1 Attach field to type (some combination of exporting configs and following a recipe for creating/copying config files).
1.1 More unit tests. (Not completely sure how/where we're testing fields.  Try setting and saving them?)

**Comment by blairlearn** [comment]
Fields and their data source in the Summary XML document.

# Fields
## Common Fields
* [Page Title](Common-Fields#Page-Title) - load from `/Summary/SummaryTitle`
* [Short Title](Common-Fields#short-title) - load from `/Summary/AltTitle[@TitleType = 'Short']`
* [List Description](Common-Fields#list-description) - load from `/Summary/SummaryMetaData/SummaryDescription`
* [Syndication Keywords](Common-Fields#syndication-keywords) - load from `/Summary/SummaryMetaData/SummaryKeyWords/SummaryKeyWord`
* [Posted Date](Common-Fields#posted-date) date_first_published - load from `/Summary/DateFirstPublished` if present, null otherwise.
* [Updated Date](Common-Fields#updated-date) - load from `/Summary/DateLastModified` if present, null otherwise.
* [Public Use](Common-Fields#public-use) Always set true


## Unique Fields to This Content Type

* **CDR ID** Database identifier from the CDR
* **Summary Type** One of "Genetics", "Integrative, alternative, and complementary therapies", "Prevention", "Screening", "Supportive care", or "Treatment". Load from `/Summary/SummaryMetaData/SummaryType`
  * (Is this still needed?)
* **Audience** One of "Patients" or "Health professionals". Load from `/Summary/SummaryMetaData/SummaryAudience`
  * (Is this still needed?)


## Sections

This is a collection of top-level sections (displayed as individual pages), each composed of a

* **Section Title:** The title for this section. Load from `/Summary/SummarySection/Title`
* **Section ID:** Unique (within this document) identifier for this section. Load from `//Summary/SummarySection/@id`
* **HTML:** The actual markup for the section
