### ISSUE TITLE
PDQ Documents (Cancer and Drug Info) have Long Descriptions > 320 characters.

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#1653]
In the CDR, the Long Description field for both Cancer and Drug Info Summaries has a maximum length of > 320 characters. The [Meta Description shared field](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Common-Fields#meta-description) is defined as a maximum of 320 characters.

**Comment by blairlearn** [comment]
Per @bkline, there are 21 cancer information summaries on production with long descriptions > 320 characters.

**Comment by lburack** [comment]
@blairlearn @bkline - we are updating the meta description field to allow 600 characters (#1663). SEO guidance still remains that meta descriptions should really be around 320 characters, with the most important, keyword-rich information in the first 160 characters. But the change request will accommodate the 21 summaries.

**Comment by bkline** [comment]
OK. When the original requirements said I could only store 320 characters in that field, without specifying what behavior should kick should longer values be encountered, I assumed that meant we should go ahead and store the first 320 characters (following the guidance from the similar discussions we had about what we should do with syndication keywords values which would not fit in the field). It turns out, however, that @bryanpizzillo was horrified that I would read the requirements this way. Therefore I need to ask explicitly -- in the unlikely event that I get a summary which exceeds 600 characters, should I:
1. store the first 600 characters and log the truncation; or
2. fail publication of the document; or
3. fail the entire publishing job; or
4. modify the schema preventing such documents from being saved as valid?
