### ISSUE TITLE
Content editors are unable to glossify on Dev

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1716]
Logged into dev as a content editor (my own role, victoria.sun) and I was unable to glossify. When I click the glossification button, I get the following error:

![image](https://user-images.githubusercontent.com/31222859/57711841-85b7ab00-763d-11e9-9146-5090b5a86634.png)

I am able to log in as an admin and glossify.

**Comment by bkline** [comment]
I have tracked this down in the debugger to yet another bug in Drupal. The problem kicks in when the `AccessAwareRouter` creates a `Request` object which it uses to find a match with the available routes, passing in only the `$pathinfo` string for the `Request` object constructor's first argument, letting the `$method` argument default to `GET`.

In this case the bug has already been reported (more than once, as it turns out).

https://www.drupal.org/project/drupal/issues/2557469
https://www.drupal.org/project/drupal/issues/3048288

Those are the two I found (might be more). Each of them has a patch. Each patch avoids the problem. The [first patch](https://www.drupal.org/files/issues/preserve_request-2557469-5.patch) replaces `Request::create($pathinfo)` with `Request::createFromGlobals()`. The [second patch](https://www.drupal.org/files/issues/2019-04-15/route-method-exception-path-fix-3048288.patch) catches the `MethodNotAllowed` exception in the `isAdminPath()` method and returns `FALSE`. The reporter for the first issue has been having a hard time convincing the core team that the bug is real, which has a familiar ring to it. Do you care which patch we use, @bryanpizzillo?

**Comment by bkline** [comment]
Here's the logic flow for what's going on when the AJAX call to the glossifier fails.

1. the `ContainerAwareEventDispatcher`'s `dispatch()` method is invoked.
2. each of the event listeners is invoked
3. one of these listeners is `onKernelRequestLanguage()` of the `LanguageRequestSubscriber` class
4. this listener is invoked and calls `$this->setLanguageOverrides()` after determining that this event represents the master request
5. that method needs the current language, so it invokes `$this->languageManager->getCurrentLanguage()`
6. the language manager invokes `LanguageNegotiator::initializeType()` with `'language_interface'` as the type
7. this method loops through all of the enabled negotiators and calls `negotiateLanguage()` for each negotiator's method
8. the `language-user-admin` negotiator makes a bunch of checks, one of which is determining whether the current request uses an admin path (`$this->isAdminPath($request)`)
9. `isAdminPath()` calls `$this->router->match($path) to get the information about the route that matches the request
10. `AccessAwareRouter`'s `match()` creates a new `Request` object using just the path string, leaving out the method, which defaults to `GET`, ignoring the fact that our request is a `POST` request
11. that `Request` object is passed to `AccessAwareRouter`'s `matchRequest()` method
12. that method passes invokes the `Router` class's `matchRequest()` method
13. all of the candidate routes matching this request are collected
14. the `applyRouteFilters()` method is invoked to weed out routes which can't be used
15. there are four filters installed, the first of which is `method_filter`, which takes our three candidates (`rest.pdq_glossifier_api.POST`, `rest.pdq_api.DELETE`, and `rest.pdq_api.GET`) and eliminates all but the last (because it thinks we've submitted a `GET` request
16. the `Router` implementation of `matchRequest()` then calls `$this->matchCollection()`
17. this method gets the _actual_ method used for our request (`$method = $this->context->getMethod()`) and because that's `POST` and the only candidate route left standing allows only `GET` that route is also removed from the running
18. since no match was returned by `matchCollection()` `Router`'s `matchRequest()` throws `MethodNotAllowedException`

When the current user has said she doesn't care what language is used for the admin pages, the call to `isAdminPath($request)` in step 8 above is avoided, because PHP's short-circuiting logic skips it (reformatted to avoid scrolling caused by ridiculous line lengths):

```php
  /**
   * {@inheritdoc}
   */
  public function getLangcode(Request $request = NULL) {
    $langcode = NULL;

    // User preference (only for administrators).
    if ($this->currentUser->hasPermission('access administration pages') &&
       ($preferred_admin_langcode = $this->currentUser->getPreferredAdminLangcode(FALSE)) &&
      $this->isAdminPath($request)
    ) {
      $langcode = $preferred_admin_langcode;
    }

    // Not an admin, no admin language preference or not on an admin path.
    return $langcode;
  }
```

**Comment by bkline** [comment]
Other related Drupal core issues:

https://www.drupal.org/project/drupal/issues/2857132
https://www.drupal.org/project/drupal/issues/2706241
