### ISSUE TITLE
Figure out what to do with Article/General/Topic -> Mini Landing Lead Images

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#1760]
Mini landing does not have a body nor lead image. We are moving the body content to a content block. The lead image needs to be moved into a embedded image in that block. (If possible)

**Comment by VictoriaSunNIH** [comment]
We should find the order of magnitude of this problem - to see if this is a content cleanup post-migration task.

**Comment by lburack** [comment]
I put a JIRA ticket in for this on Friday: https://tracker.nci.nih.gov/browse/OCECREATIV-3102. This isn’t just an issue for articles migrating to mini landing; if an image (with article crop)  is slotted onto a topic page currently, that displays in the top right of the page. 
In any case, there’s only about 15 pages with this issue. I think some of these might not even need the image, but I’ll reach out to content owners to verify this week. 

@VictoriaSunNIH, @bryanpizzillo — With under 15 pages to update, I think this could be handled as a migration task, rather than creating duplicate images (with not all crops) to handle in percussion now.
