### ISSUE TITLE
Align markup for /node/{node}/syndication routes to match www.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#1804]
* Example of a PDQ Cancer Information Summary:
  * Pruritus (PDQ®)–Patient Version (https://www.cancer.gov/PublishedContent/Syndication/1991.htm)
* Example of an Article:
   * Learning to Relax (https://www.cancer.gov/PublishedContent/Syndication/1037684.htm)

Both of these URLs should have YAML content, but I cannot add the Node IDs because they can change upon load.

Note: Syndicated content has a special tagline added to the end of the page:
```
<span id="nciLink">This content is provided by the National Cancer Institute (<a href="http://www.cancer.gov">www.cancer.gov</a>)</span>
```

**Comment by bryanpizzillo** [comment]
@blairlearn Can please get the Percussion page templates for Articles, Fact Sheets and PDQ Summaries and attach to this ticket?

**Comment by sarinapadilla** [comment]
/Users/padillasr/Documents/nvcgPgArticle
/Users/padillasr/Documents/nvcgPgFactSheet
/Users/padillasr/Documents/nvcgPgCancerInfoSummary
/Users/padillasr/Documents/nvcgPgPDQDrugInfoSummary

Notes about these items:
* The $isPublish variable is assumed to be true - since we no longer have preview templates in Drupal.
* The $locale variable is either English or Spanish, and the $onThisPageText is "En esta página" if Spanish or "On This Page" if English.
* The Output<Item>AsSnippetOrPreview macros are just an indication that the markup of those items should match the field/paragraph templates that exist now for those items (i.e. Related Resources, Citations, Dates, Article Image, etc.)
