### ISSUE TITLE
Tablet display of Blog Right Rail is incorrect

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1899]
On Prod, at tablet breakpoint, the right rail on blog series/blog posts displays as 3 columns side by side.  On Dev, the right rail is displaying as stacking.  We need to update the display to be the same as prod.

Example on prod (https://www.cancer.gov/news-events/cancer-currents-blog): 
![image](https://user-images.githubusercontent.com/31222859/58982189-e439fa00-87a1-11e9-8275-f9b99122cc45.png)

Example on dev (https://www-dev-ac.cancer.gov/news-events/cancer-currents-blog): 
![image](https://user-images.githubusercontent.com/31222859/58982266-0a5f9a00-87a2-11e9-9310-84f3a048187e.png)

**Comment by BrendanBeltzNIH** [comment]
Ok, so this one is an interesting case that I'd just like to ask for input as to whether it's worth pursuing a (maybe non-existent) more complicated solution than just css changes.

Essentially, Page Manager has it's own layout system with regions and uses the region id to create a wrapper div with the class block-region-<REGION_ID> (in our case 'block-region-second').

![image](https://user-images.githubusercontent.com/34315527/58990701-86fb7400-87b4-11e9-9ab4-b287abf43712.png)

This is getting done programmatically in the page manager plugin PageBlockDisplayVariant.php buildRegions method.

![image](https://user-images.githubusercontent.com/34315527/58990801-d346b400-87b4-11e9-89e7-c1ec59980423.png)

It may be possible to at least attack this markup somewhere along the render pipeline (since we can't simply override a template), but is it worth it?
