### ISSUE TITLE
DOC Carousel and Social Media row on Home Page displaying incorrectly

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#1906]
Please triage the display issues with the DOC carousel and social media icons on the home page. 

See Migration ODE http://ncigovcdode118.prod.acquia-sites.com/homepage

![image](https://user-images.githubusercontent.com/28450779/59031495-dfbd2200-8831-11e9-9ff8-7e1eaa2c69e7.png)

![image](https://user-images.githubusercontent.com/28450779/59031536-f5cae280-8831-11e9-8db2-50a02fc7dd70.png)

Compare with same content on https://www-blue-dev.cancer.gov/

![image](https://user-images.githubusercontent.com/28450779/59031600-201ca000-8832-11e9-90e0-2c91107db7d4.png)

![image](https://user-images.githubusercontent.com/28450779/59031643-42162280-8832-11e9-95fd-f0b9355456d0.png)

**Comment by BrendanBeltzNIH** [comment]
There are two parts to this. The styles haven't been ported from HomePage for some reason (should have been done when HomeLanding was created). In addition, the image references to publishedcontent images aren't going to work because that's not where we keep our images anymore.

**Comment by BrendanBeltzNIH** [comment]
So, I did this one as far as I could (the carousel and pattern injector). The social media icons is a reference issue. Instead of referencing '/PublishedContent/...' hardcoded images will need to go to '/profiles/custom/cgov_site/themes/custom/cgov/static/...' (don't quote me on that :p ). I think these are in the content for the home page no? That's where the change needs to be made. Since it's only 4 icons on two pages, I would suggest doing it manually post-migration.

**Comment by BrendanBeltzNIH** [comment]
More perpplexingly is that on the spanish version of the homepage, where we use youtube and govdelivery (why are they different, this has always broken my brain!?) and reference the images in publishedcontent, well... they aren't in that folder in the new repo, or the old. huh?

**Comment by BrendanBeltzNIH** [comment]
I'm breaking the second part into a second issue so that it's not lost when the PR autocloses this.
