### ISSUE TITLE
Styling is missing on the years on Press Release dynamic list pages

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1915]
Spacing and pipes between years not appearing on Press Release pages:
Examples:
- http://ncigovcdode118.prod.acquia-sites.com/news-events/press-releases/2017
- http://ncigovcdode118.prod.acquia-sites.com/news-events/press-releases/2016

**Comment by BrendanBeltzNIH** [comment]
So, I'll look closer at how that line is dynamically built to insert the pipe characters between the a tags (hopefully not manually), but I also notice that it's not turning off the link for the current page (as in being plain text rather than a circular link). Also, is all the legacy percussion stuff supposed to be there?

![image](https://user-images.githubusercontent.com/34315527/59050976-c5973a00-8859-11e9-8f21-374d317db451.png)

**Comment by BrendanBeltzNIH** [comment]
Bryan tells me there's nothing dynamic and it's just a block on percussion. So this seems to be a migration thing. the content is just text and relative links, that should drop in fine. I don't think I can do anything on this end.

**Comment by BrendanBeltzNIH** [comment]
Yeah, this is a content issue again. Not styling. Perhaps just cleaning it up and adding in the pipes manually after migration is the simplest answer.

**Comment by adriancofie** [comment]
@BrendanBeltzNIH  @VictoriaSunNIH  Assigning to me;  this is a side-effect of another issue. Will be resolved via the update_content_block migration running.

**Comment by adriancofie** [comment]
The fix was merged into develop, needs to be confirmed.

**Comment by VictoriaSunNIH** [comment]
Confirmed. This can be closed.
