### ISSUE TITLE
MyPart Inline Feature Cards are getting the wrong hover color

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#1946]
The hover color for the inline feature cards on migrated content for microsites are cranberry and incorrect.  On Prod, they are orangey.

Example URLs where its incorrect:
- http://ncigovcdode178.prod.acquia-sites.com/rare-tumors/rare-bone-tumors/adamantinoma
- http://ncigovcdode178.prod.acquia-sites.com/rare-tumors/rare-digestive-system-tumors/sdh-deficient-gastrointestinal-stromal-tumor-gist
- http://ncigovcdode178.prod.acquia-sites.com/rare-tumors/rare-endocrine-tumor/anaplastic-thyroid-cancer
- http://ncigovcdode178.prod.acquia-sites.com/rare-tumors/rare-soft-tissue-tumors/inflammatory-myofibroblastic-tumor
- http://ncigovcdode178.prod.acquia-sites.com/rare-tumors/rare-soft-tissue-tumors/synovial-sarcoma
- http://ncigovcdode178.prod.acquia-sites.com/rare-tumors/rare-vascular-tumors/angiosarcoma

Example on Prod:
https://www.cancer.gov/nci/pediatric-adult-rare-tumor/rare-tumors/rare-bone-tumors/adamantinoma

**Comment by arcepaul** [comment]
Set up my local with migrated content for the ability to test changes.  We found out, however that microsite styling overall was not really looked at.  In addition to the fix for the topic feature cards, issues fixed were:

- [ ] margin below logo was acting up and causing a gap when it went sticky, replaced the .micro-a margin-top rule to eliminate the gap
- [ ] the border for feature cards was not as dark as it should be, it looks like a debugging border was left in on embedded-entity
- [ ] the multimedia-slot in the body on the microsite home page had a gap, fixed targeting last-child and scoped to microsite so as not to break other stuff

**Comment by arcepaul** [comment]
Addressed and closed in PR #2028
