### ISSUE TITLE
CTHP Research Card and Guide Card Spacing is now too wide

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2005]
Some kind of regression happened with the last build, and the spacing on CTHP Research and Guide Cards (View More Information) is too much.

http://ncigovcdode176.prod.acquia-sites.com/types/bladder versus https://www.cancer.gov/types/bladder

Incorrect spacing on View more info :
![image](https://user-images.githubusercontent.com/31222859/59566869-c9824380-9033-11e9-9d24-114de4b909ba.png)

Correct spacing View more info: 
![image](https://user-images.githubusercontent.com/31222859/59566864-bf604500-9033-11e9-9beb-fcc867f6cf54.png)

Incorrect spacing on Research card:
![image](https://user-images.githubusercontent.com/31222859/59566874-d69f3280-9033-11e9-9153-56daf5efd5e1.png)

Correct spacing on research card:
![image](https://user-images.githubusercontent.com/31222859/59566876-e0c13100-9033-11e9-8b8e-ca5080284c30.png)

**Comment by BrendanBeltzNIH** [comment]
The problem with these stories is that they are being reported in good faith (ie, here is a bug, can you fix this bug here, that is all) when because of the tight coupling of our old css to percussion based structure means any number of side effects can occur. Without comprehensively capturing the requirements and acceptance criteria going in, it's inevitably the case of plugging one leak and three more springing up.

With that in mind, I'm going to fix what I've been asked, but I recommend you put nadia on it for a few minutes to double check the CTHP changes.
