### ISSUE TITLE
CTHP Breadcrumbs are not aligned with the page title

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#2006]
The breadcrumbs on CTHP are not aligned with the page title:

![image](https://user-images.githubusercontent.com/31222859/59566897-1e25be80-9034-11e9-829c-7061093d0135.png)

Example URLs:
- http://ncigovcdode176.prod.acquia-sites.com/types/bladder
- http://ncigovcdode176.prod.acquia-sites.com/types/bladder/hp
- http://ncigovcdode176.prod.acquia-sites.com/espanol/tipos/vejiga
- http://ncigovcdode176.prod.acquia-sites.com/espanol/tipos/vejiga/pro

**Comment by BrendanBeltzNIH** [comment]
When the CTHP templates were created, the markup didn't quite match. This is because there are custom breadcrumb classes that the CTHP css uses to have a custom padding. Either the breadcrumb templates need to add in those classes based on the bundle type (meh) or we can simply add in the custom class higher up (so we can put it in the cthp page template) or (ideally) we can do it all without adding classes at all and just scoping the rules to CTHP.scss.

Old custom rules:

![image](https://user-images.githubusercontent.com/34315527/59568857-47077d00-904f-11e9-8fa1-a68e573008c2.png)

Old custom markup:

![image](https://user-images.githubusercontent.com/34315527/59568861-52f33f00-904f-11e9-88db-ae162625b5e1.png)
