### ISSUE TITLE
Blog Series page - List Thumbnails setting not working

### ISSUE THREAD

**Issue by claireblaustein** [NCIOCPL/cgov-digital-platform#2109]
Turning off list thumbnails on the blog series isn't working - the thumbnails still show. This setting is needed for DCEG, whose blog will not display images (as their content migrating in as blog posts does not have images)

https://www-dev-ac.cancer.gov/research/key-initiatives/ras/ras-central/blog

![image](https://user-images.githubusercontent.com/39384914/60295049-cb2fef00-98f0-11e9-9623-afe9622267e7.png)

**Comment by daquinohd** [comment]
This is caused by the following block in `node--cgov-blog-series--full.html.twig`:

```
 {# Draw the appropriate view using twig_tweak. Only draw thumnail vers for now. #}
 {# if field_show_list_thumbnails #}
 {{ drupal_view('cgov_block_blog_posts', 'block_bp_list_th', node.id) }}
 {# else drupal_view('cgov_block_blog_posts', 'block_bp_list', node.id) #}
 ```

The logic was commented out because `field_show_list_thumbnails` is always evaluating to false. It has been checked against true/false, 0/1, and string values. This will require a template and possibly a configuration change.
