### ISSUE TITLE
Users should not be able to use form login on SSO protected environment.

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#2121]
Accounts that are blocked from using form logins can STILL login without getting an error. They are kicked to the home page in what appears to be a successful login, and then they ask questions like, why can't I see the admin bar.

**Comment by blairlearn** [comment]
In the `simplesamlphp_auth` module, there's a `SimplesamlSubscriber` class with two methods: `checkAuthStatus()` and `login_directly_with_external_IdP`.  Both methods are used to subscribe to `KernelEvents::REQUEST`. 

If you’re not SAML authenticated, and form isn’t allowed, `checkAuthStatus()` sends you to `/` (Not `/<front>` and not `user.login`).  That causes this issue.

* Additionally, there is a loop which arises when a user is authenticated on SSO, but not set up as a Drupal user.

This is because
* If you’re not logged in, and you’re trying to go to `user.login`, `login_directly_with_external_IdP()` throws you to `simplesamlphp_auth.saml_login`.
* IIRC, if you’re using SSO and you’re not recognized by the system, you get directed to `user.login`.
