### ISSUE TITLE
Blog Category - Cache Issues

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#2180]
A Blog Category (Taxonomy Term) was updated, but the change did not apply to the Categories block on all the pages within the blog. (This was Cancer Currents)

I'm creating this issue because I:
1) had a tab open on https://www-prod-acsf.cancer.gov/news-events/cancer-currents-blog?topic=fda-approvals. The page title was "FDA Drug Approvals - Cancer Currents Blog" and the right rail category was "FDA Drug Approvals"
2) In another tab, I had www-cms.cancer.gov open and I changed the blog taxonomy term to remove 'Drug' so the category was "FDA Approvals"
3) On prod-ascf, I see my update when I'm on any of the other category pages (e.g., https://www-prod-acsf.cancer.gov/news-events/cancer-currents-blog?topic=disparities), but **not** when I'm on the fda-approvals page itself.

If this doesn't make sense, @bryanpizzillo can better explain/update this.

**Comment by bryanpizzillo** [comment]
A change to a the `name` of a Blog Category should trigger a cache invalidation of all the pages displaying the Categories block. Since the Categories block is dynamic and shared across all blogs, you need to be careful about what gets invalidated. (If you invalidated just the block ID, you would potentially clear out all blogs from the cache)

Since all pages within a blog show the block, it would be simplest to invalidate the blog series if a category is updated. (Just make sure the blog series node id is a cache tag on every page)

**Comment by kalidindir** [comment]
@lburack @VictoriaSunNIH
http://ncigovcdode256.prod.acquia-sites.com

**Comment by VictoriaSunNIH** [comment]
@lburack - I tested this by changing the biology category.  I see that the right nav changed on all pages, as well as the page title.  I also created a new post and tagged it and saw the correct name there.  Waiting on you to retest!

**Comment by lburack** [comment]
@VictoriaSunNIH @kalidindir — this also passes my IA review. I'll test the other tickets related to the PR #2346 in the morning.
