### ISSUE TITLE
Broken links on DCEG Page Not Found

### ISSUE THREAD

**Issue by goldenec** [NCIOCPL/cgov-digital-platform#2310]
The page not found template results in broken links (cancer type and Get in touch) on DCEG subdomain. Reproduce the issue here: https://dceg.cancer.gov/z

Possible approach, as discussed with @adriancofie: develop a content block to customize Page Not Found for all microsites (subdomains and those on cancer.gov)

**Comment by adriancofie** [comment]
The approach I would lean toward for this is creating an 'Error Page Content'  Raw HTML Block.
Each Drupal site would then be able to treat this like  we treat other content in the system and adjust as needed.

The Block would be embedded in the existing page--404  twig template, replacing the current existing content area. 

For the block to be accessible within the twig template, it would be added to the variables array using a preprocess function.


Other less ideal solutions in order of increasing magnitude:

- Sam as above but place it via twig_tweak.

- Create a new region, used only on error pages, containing said block. Update the existing templates.

- Create a content type for error pages, and instead of using a theme suggestion like we are now for en/es/403/404 use multilingual and the built-in 403/404 handling logic.

- Customize core block layout logic  to allow restricting blocks to error pages (currently you can only restrict to certain paths or content types). 

- Some combination of the above.

**Comment by bryanpizzillo** [comment]
I like "Create a new region, used only on error pages, containing said block. Update the existing templates" over the preprocessor. (Still using raw html of course)

One concern I do have is how this may affect the ability to create fast 404 pages in the future. We get a lot of 404s. However, I think this is a good approach for now.

@welshja any Analytics needed for DCEG 404 *content* that differ from CGOV? (The page level metadata should work now without issue, this question is more for tracking of links and buttons in the content...)

**Comment by amydugan** [comment]
@arcepaul - you mentioned you may need some additional information on what the 404 pages should look like/what should be included. 
Reach out to @lburack if you have follow up questions on how the blocks should look/what they should.
I'll reach out to Andrew on the question about Analytics needed for DCEG 404 content.

**Comment by goldenec** [comment]
Hi, @arcepaul. Here's text for the DCEG 404 page:
<h1>Page Not Found</h1>
<p>We can't find the page you're looking for.</p>
<p>Are you looking for a DCEG staff member? Browse our <a href="/about/staff-directory">staff directory</a>. 
<p>You can also learn more about <a href="/research">our research</a> or <a href="/about/contact-dceg">contact us</a>.</p>

**Comment by amydugan** [comment]
From Andrew re: analytics

> I don’t believe there are any different analytics needs for microsite 404 pages. We’ll be able to tell from the prop 1 value if someone hit a microsite 404, so I don’t think there are any special considerations there. Looking at the layout, we would simply want to know: which link was clicked, if a search was submitted from the 404 search and what was entered in the search box.

**Comment by amydugan** [comment]
@arcepaul - did you get what you needed from the conversation with Bryan that migrated from the question I was asking Blair about the Search on the DCEG 404 page? What I wrote down from the conversation is below, but likely missed some of the nuance:

- The search submit needs to go to the correct path

- The block will need to reference DCEG's search results page /dceg-search/results

**Comment by arcepaul** [comment]
@amydugan 
Yes, I think everything is good to go.  Going to throw it up onto an ODE now.  Thanks!

**Comment by goldenec** [comment]
The custom block in the Page Not Found region passes IA review for DCEG. Search is not working, but i can see that the search points to action="/dceg-search-results", and it is expected that search will work on the live site.
