### ISSUE TITLE
Fix click event analytics on CTHP and PDQ pages so that -health_professional or -patient doesn't stack

### ISSUE THREAD

**Issue by amydugan** [NCIOCPL/cgov-digital-platform#2327]
Go to any CTHP or PDQ page, look at the analytics debugger and you will see that the page name is set to a value like "www.cancer.gov/types/liver/hp - health_professional". Click the toggle between patient and HP and observe the same. As you go back to the HP page or if you elicit click events on the page, you'll see that the "- patient" or "- health_professional" begin to stack and add multiple times over. This was previously fixed for post events (#2201 ) BUT click events are still an issue. 

The fix that was previously applied to for posts was:  

- Cleaned up setNciPageNameAdditions() and set pageName to omit concatenated local pn values

This is messing up analytics reports and needs to be fixed.

**Comment by arcepaul** [comment]
I've been clicking around and have not yet been able to see this stacking behavior rear its head in Omnibug

<img width="1434" alt="Screen Shot 2019-08-14 at 9 22 50 AM" src="https://user-images.githubusercontent.com/45469809/63024408-2902a100-be75-11e9-99ac-cccb73d1d011.png">

**Comment by amydugan** [comment]
@arcepaul - I'm going to have Andrew sync with you on this issue. He actually can't reproduce it in this way either, but he can give you more info on the impacted analytics file, which is significantly skewing the monthly dashboard wrt click events.

**Comment by welshja** [comment]
@arcepaul , not sure if you and Andrew were able to get to the bottom of this or not, but the issue is occurring in click events on CTHPs or PDQs. If you go to https://www.cancer.gov/types/liver, open omnibug and then click on a link in a card, you'll see the issue occur in the click event. 

![image](https://user-images.githubusercontent.com/52838301/63271394-0ce17400-c268-11e9-836b-d4b6c4adf0d3.png)
