### ISSUE TITLE
Remove Drupal-based SWS App module

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3019]
### Issue description
Now that SWS App is a generic app module, it is no longer needed. Remove `docroot/modules/cgov_sitewide_search` app module, remove JS/CSS, do what is needed to uninstall it on prod, and update any yaml content files to reference the generic app module as needed. Basically purge it and don't break anything.

> **ESTIMATE** TBD

**Comment by VictoriaSunNIH** [comment]
@blairlearn, @arcepaul - this looks to have been resolved based on the commits. can you close this if it is? thanks!

**Comment by blairlearn** [comment]
@VictoriaSunNIH and @arcepaul - this is _not_ resolved. This issue is for the removal of the Drupal code for the old module.

 The commits in question could (should?) have referenced #3021 (Disable Drupal-based SWS Module) instead.  The changes @arcepaul made were to remove the front-end support for the old SWS module, the changes I made in #3021 were to remove it from the list of available app-module types.
