### ISSUE TITLE
Remove Drupal-based Glossary App Module

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/cgov-digital-platform#3020]
### Issue description
Now that Glossary App is a generic app module, it is no longer needed. Remove `docroot/modules/cgov_glossary` app module, remove JS/CSS, do what is needed to uninstall it on prod, and update any yaml content files as needed. Basically purge it and don't break anything.

> **ESTIMATE** TBD

**Comment by VictoriaSunNIH** [comment]
@blairlearn, @arcepaul - this looks to have been resolved based on the commits. can you close this if it is? thanks!

**Comment by blairlearn** [comment]
@VictoriaSunNIH and @arcepaul - this is _not_ resolved. This issue is for the removal of the Drupal code for the old module.

 The commits in question could (should?) have referenced #3022 (Disable Drupal-based Glossary App Module) instead.  The changes @arcepaul made were to remove the front-end support for the old SWS module, the changes I made in #3022 were to remove it from the list of available app-module types.
