### ISSUE TITLE
Update Factbook charts to 2020 data

### ISSUE THREAD

**Issue by allymh** [NCIOCPL/cgov-digital-platform#3044]
Most of the JS files for Fact Book FY20 have been updated. Next step is for @blairl-nih to put the files into version control and update ODE. Files will be emailed to Blair.

### Notes
I am waiting to receive data for two more charts.

**Comment by allymh** [comment]
Update: Data has been provided and last two Highcharts updates needed have been logged in Git.
https://github.com/NCIOCPL/cgov-digital-platform/issues/3130
https://github.com/NCIOCPL/cgov-digital-platform/issues/3131

**Comment by blairlearn** [comment]
Lacking a better place to put these notes.....  (@allymh - this is mainly bookkeeping)

In order to keep this separate from the regular release cycle, we're going to treat this as a hotfix, but because the approval period is likely to take longer than a typical hotfix, the pull request will target the `factbook-2020-update` branch.  If necessary, `factbook-2020-update` will be updated to track any deployments  that take place before the final `hotfix` branch is created.
