### ISSUE TITLE
Cannot embed media items in related resources

### ISSUE THREAD

**Issue by blairlearn** [NCIOCPL/cgov-digital-platform#3466]
### Issue description
Page save fails with a validation message if the related resources section includes a media item.

> **ESTIMATE** TBD

### Steps to reproduce the issue

1. Login to the CMS
2. Create a new press release (may occur for other content types as well)
3. In the related resources section
   1. Select "Add Media Link"
   2. Expand the "Link" link.
   3. Click "Select media"
   4. Choose any published media item (tested with image and infographic)
   5. Click "Select media"
   6. At the bottom of the page, click the "Save" button.

### What's the expected result?
- The content item is saved and a preview version is displayed

### What's the actual result?
- A page validation message appears with the message "This entity (media: xxxxxxx) cannot be referenced."

### Additional details / screenshot
- ![image](https://user-images.githubusercontent.com/21063180/181843340-1469356b-df4a-4883-8cbc-4f87c67b2bc8.png)

**Comment by bryanpizzillo** [comment]
@blairlearn Images (cgov_image & cgov_contextual_image) types cannot be set as a [target on a media link](https://github.com/NCIOCPL/cgov-digital-platform/issues/1145), so they are [expected to not work when those types are added](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Paragraph-Type-Links#media-link-1). Adding a infographic media type worked on https://ncigovcdode479.prod.acquia-sites.com - so if adding infographic media items did not work on the upgrade ODE, then there is an issue with the upgrade. (Also note that there are cgov_contextual_images that have the word infographic in the title, and are NOT actual cgov_infographic media items, and they would not work)

The selection that is show is a view for all media, this is because we cannot limit the specific type without introducing a circular dependency. This is semi-related to https://github.com/NCIOCPL/cgov-digital-platform/issues/3225. However, the fix in 3225 is only for the reference field -- the view that drives the selection would need to have a similar plugin made to filter. Drupal actually validates the types in the list to ensure the modules are installed.

**Comment by blairlearn** [comment]
@bryanpizzillo I _thought_ for sure I'd reproduced it with infographic. (Definitely used the type filter.)  Trying it again now though, it definitely works.

So, closing as a known limitation.
