### ISSUE TITLE
Print Style Cuts Off H2 on Article Page

### ISSUE THREAD

**Issue by bennettcc** [NCIOCPL/cgov-digital-platform#3596]
### Basic Information ###
- Issue: Identified an instance where the H2 is separated on a print page. Wonder if it is due to the lead image or OTP as part of the article page.
- Desired Outcome: For the H2 to not be separated and to be one one line.
- Notes: see this also occurs in production, so is an existing issue. Need to determine if this is something we want to address. 

### Steps to Reproduce ###
1. Navigate to webpage with identified issue (https://www-test-acsf.cancer.gov/about-cancer/understanding/what-is-cancer)
2. Click the "Print" icon
3. See that the H2 is separated on the print screen

### Screen Shots ###
![Image](https://user-images.githubusercontent.com/102998716/194376232-eb76de84-67a1-4ae6-9e66-8bdacee144e8.png)

**Comment by bryanpizzillo** [comment]
@meglake This happens on the current theme. It also happens because this is legacy css. We said we were not going to touch inner pages as part of the release. Also, this just happens because of the callout on the page being at the top as well.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/11215649/195233308-d03717bc-8853-4122-8463-e7bd478d183a.png">

**Comment by bennettcc** [comment]
Thanks @bryanpizzillo - @meglake, sounds like an item to move to the backlog then and not touch for mvp1?

**Comment by meglake** [comment]
@bennettcc lets call this a non-issue and I'm closing this ticket. This will be addressed as we move inner pages to align with the DS.
