### ISSUE TITLE
Spike for CK editor

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#3846]
Spike for what's needed to update CK editor. Compile a list of which modules will need to be upgraded before working on CK editor.

- Embed module update - dependency for CK editor
- Others?
- Other updates needed?

### Dependent  tickets:

- [x] #3545 
- [ ] #3541 - Token/Token Filter

- create follow-up tickets

### Resources:
- [App Module List](https://nih.sharepoint.com/:x:/r/sites/NCI-OCPLPlatformSupport/Shared%20Documents/Boundary%20-%20CGDP/Drupal%20Upgrades/Drupal%2010%20Upgrade/CGDP-D10-Support.xlsx?d=wbf40f4862e9a4ec2bf793eb5138f6021&csf=1&web=1&e=DFVkhJ)

**Comment by navsunka** [comment]
My findings:

**Linkit** 
Linkit module is compatible with Ckeditor 5 Latest Version :- 
6.1.0-rc1(Drupal >=10.1)
6.0.0-rc1(Drupal <=10.1)


**entity_embed** 
Entity Embed isn't Drupal 10 ready.
Latest version : 8.x-1.4(Drupal 10 compatible (but not CKEditor5 yet))
Ckeditor 5 development is in progress (https://www.drupal.org/project/entity_embed/issues/3272732)


**token_filter**
token_filter isn't Drupal 10 ready.
version :- 2.0.0  released 7 February 2023
Ckeditor 5 Issue is RTBC (https://www.drupal.org/project/token_filter/issues/3262052) -


**pdq_glossifier**
Steps to create a Ckeditor 5 plugin (https://www.qed42.com/insights/coe/drupal/everything-you-need-know-about-ckeditor-5-integration-drupal-9)


**embed**
Issue is there with Ckeditor5
Latest Version:- 8.x-1.6
Issue with Ckeditor 5 :- Development is in progress (https://www.drupal.org/project/embed/issues/3309747)


**Token**
Issue is there with Ckeditor5
Latest Version:- 8.x-1.11
Ckeditor 5 Issue is RTBC (https://www.drupal.org/project/token/issues/3334784)

@bryanpizzillo @santwuma

**Comment by navsunka** [comment]
1.	Created a test article content for all the 3 types of text editors and applied every plugin available except glossary.
2.	Updated all the below modules to work with CKEditor 5.
•	"drupal/embed": [1.x-dev@dev]
•	"drupal/entity_embed": "^1.4"
•	"drupal/linkit": [^6.0@RC]
•	"drupal/token": "^1.12"
•	"drupal/token_filter": "^2.0"
3.	Applied below patches for both embed and entity embed.
•	"drupal/entity_embed": {
"3272732 : Drupal 10 & CKEditor 5 readiness": “https://www.drupal.org/files/issues/2023-06-19/entity_embed-3272732-93.patch”
•	"drupal/embed": {
"3309747 : CKEditor 5 compatibility": “https://www.drupal.org/files/issues/2023-06-07/3309747-ckeditor5-compatibility.patch”
4.	Configured CKEditor 5 in Simple, Steamlined, and FullHTML editors.
5.	While configuring CKEditor5 in editors, Disabled style button as we have separate button for headings. Also, rearranged styling order for Align images and Display embedded entities as shown in the error message while saving the page.
6.	Images need to be in SVG for all entity embed button icons to appear.
(https://www.drupal.org/project/embed/issues/3310328)
7.	Updated name to CKEditor5-stylesheets in ncids_trans.info.yml
8.	Styling issues found inside CKEditor5 but no issues found on the FE side.
9.     Started checking out glossifier to create CKEditor5 plugin.

@santwuma @bryanpizzillo

**Comment by navsunka** [comment]
I checked how to migrate custom ckeditor plugin to ckeditor5 plugin.
The only challenge is to update the JS files according to new ways written in the ckeditor5 plugins. Need help in implementing JS once we start the development.

@santwuma @bryanpizzillo

**Comment by navsunka** [comment]
After enabling CKeditor5, we have to do the steps in the link provided below to load a default theme stylesheet in CKEditor 5 because Unlike CKEditor 4, CKEditor 5 is not provided via <iframe>, so a stylesheet added via ckeditor5-stylesheets will be applied to the entire page. Depending on the contents of your stylesheet, it may be necessary to provide an additional ckeditor5-specific stylesheet.

https://www.drupal.org/node/3259165

Apart from configuration and theme level changes, there are some css fixes required for this CKeditor styles to work.

**Linkit**

Below version of Linkit module can work with CKeditor4 and CKeditor5, no issues found when tested in local.
6.0.0-rc1(Drupal <=10.1)

**Token/Token filter**

Both are Drupal 10 ready but not CKeditor 5 ready yet, There are issues which are in RTBC. We can wait for those to be merged because we are not affected by it. We are using token in block in CKeditor and it is working fine even without applying the patches.

Current version: “drupal/token_filter": "^1.3.0”
Latest version:   “drupal/token_filter": "^2.0"

Current version: "drupal/token": "^1.9.0"
Latest version:   "drupal/token": "^1.12"

**Embed/Entity Embed**

I have updated to latest versions which are Drupal 10 ready but not CKeditor 5 yet, Development for those are still in progress and I found patches which are working fine in my local but not sure if those affect anything else. we have to look out for the stable patches for those to work without any issues.

CKeditor5 supports SVG images only, so we have to update all the entity embed icon images to SVG. There are some CSS issues in the editor for all the entity embed plugins which needs to checked after doing CKeditor5 CSS changes we mentioned earlier.

Current version: “drupal/embed": "^1.6"
Latest version:   "drupal/embed": "1.x-dev@dev"

Current version: "drupal/entity_embed": "^1.2.0"
Latest version:   "drupal/entity_embed": "^1.4"

Issues:
https://www.drupal.org/project/entity_embed/issues/3272732
https://www.drupal.org/project/embed/issues/3309747

**PDQ Glossifier**

We have to update the custom CKeditor 4 to 5 plugin. For that, we have starter kit which we can use to update the plugin but the only challenge is the JS. We need to change the whole JS files based on the new CKeditor 5 implementation and for that we require someone with JS knowledge.

https://www.drupal.org/docs/core-modules-and-themes/core-modules/ckeditor-5-module/upgrading-modules-extending-ckeditor-4-to-support-ckeditor-5
https://git.drupalcode.org/project/ckeditor5_dev/-/tree/1.0.x/ckeditor5_plugin_starter_template
