### ISSUE TITLE
CK Editor issue - Unable to see the Video Carousel in the CMS

### ISSUE THREAD

**Issue by santwuma** [NCIOCPL/cgov-digital-platform#4085]
When I am adding the Video Carousel (Display= Full, Alignment = Center), I am not able to see the video Carousel on the CMS.
Compare with the screen-shot on cms-dev (3rd screen-shot).

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/0e67683c-5ec2-41ce-a658-0671640c8b20)

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/72551a1f-02c2-42a4-9657-5b5248f9e933)

![Image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/75697303-e734-4995-a22d-4606ff8e6e98)

**Comment by navsunka** [comment]
Upon updating entity embed module, route name got changed in the contrib module because of which our custom code is failing. the issues is creditor rendering ncids_trans template instead of cgov_admin templates.
Filepath: docroot/profiles/custom/cgov_site/modules/custom/cgov_core/src/Theme/EntityEmbedPreviewThemeNegotiator.php

entity_embed.preview ----> embed.preview

**Comment by alinai** [comment]
Looks good on the ODE CMS. @navsunka, @santwuma , @sarinapadilla

**Comment by alinai** [comment]
Looks good on cms-test

**Comment by alinai** [comment]
Looks good on ODE647.
