### ISSUE TITLE
Highcharts: Inconsistency on Chart Y-axis max value

### ISSUE THREAD

**Issue by alinai** [NCIOCPL/cgov-digital-platform#4344]
### Issue description

**Issue -1**, We are noticing the following issue for the "Research Project Grants (RPGs)" chart:

 The maximum value on the Y-axis appears as 5,000 on first load and on refreshing appears as 6,000. 

url: https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/rpg

We are noticing the following issue for the "Comparison of Dollars, Positions,  and Space" chart:

The maximum value on the Y-axis appears as 7.2M on first load and on refreshing appears as 7M

url: https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/comparison

**Issue -2** , On ODE 736, for  "Comparison of Dollars, Positions,  and Space" chart, the downloaded files shows different values on Y-axis and Z-axis compared to dev-ac and Prod. No matter we refresh or we DO NOT refresh it always shows the Y-axis value as 7.2M on ODE vs. 7M on the Y-axis on dev-ac and Prod. See the screen-shot below.

@seyilonge-nci , thinks that the difference in Y-axis and Z-axis values on the downloaded file that we are seeing on the ODE is due to the  max value not being set for charts  (Issue -1) and once the Y-axis and Z-axis value is set, Issue-2 will be resolved. 

cc: @seyilonge , @laurelthrash , @kate-mashkina

> **ESTIMATE** TBD

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/1f4a9901-b1d7-4a91-b79a-1eefe436cb0f)
![image](https://github.com/NCIOCPL/cgov-digital-platform/assets/28455973/05cac012-10c8-40bb-99e2-67e068c6df5f)

- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by seyilonge-nci** [comment]
The issue here with the chart is the same for all environments, ODE, dev-ac, and prod. There's no consistency to the max value on the y-axis for the charts listed below on first and subsequent hits. This also carries on to the chart exports for all file  types as they are extracted from the displayed chart.

1. [RPGs Number of Awards](https://www.cancer.gov/about-nci/budget/fact-book/extramural-programs/rpg)
2. [Comparison of Dollars, Positions, and Space](https://www.cancer.gov/about-nci/budget/fact-book/historical-trends/comparison)
