### ISSUE TITLE
Issue with Flag Card Text Cutting off with Certain Text and Certain Browser Width

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/cgov-digital-platform#4457]
### Issue Description
For display of the flag cards on the desktop desktop breakpoint (1024-1400) when a users browser width is between 1024-1176, we are seeing longer words causing all the text to run outside of the card.

### Steps to reproduce the issue

1.  Seen on https://ncigovcdode829.prod.acquia-sites.com/test/ncids-multimedia-flag-card-test. Go to a page with a flag card and insert the word "Immunotherapy's" into the title through inspect element.
2.  Adjust the size of your browser width until you can see the issue.

### Notes
Looking at the data, about 6% of visits to the site use browsers with widths between 1000-1199 - so 94% of users would not run into this issue.

From a governance perspective, we have documented this guidance in terms of the amount of content, the length, and the best use cases for this component to help avoid this being an issue.

For someone to observe this issue, they need to be in the 6% of people viewing the site on a browser that size and have a page that was built not following the governance for Flag Card content.

While the impact is limited, this ticket is to report the issue and work on how to address going forward. 

### Proposed Change Request

The requested change is to make the switch from a single column to 2 columns begin at the Desktop-Lg breakpoint and up (>= 1200px), see the [comp](https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5719-80379&t=rgv4njGMiMuVc6Og-1) for details.

### DoR Tasks

- [x] Product (Andy) to gain approval from client on making this change
- [x] Design (@blilianyu @monika-jaeger) to make changes to comps to reflect the two columns appearing after the breakpoint reaches and exceeds 1200px (after gaining client approval)
- [x] Product (Andy) to review and approve comps
- [x] Developer to review and approve ticket and comps

### Additional details / screenshot
![image](https://github.com/user-attachments/assets/d7b2e9d4-feac-40ff-a2d5-a2db5dd18021)

### Related Tickets
* Original Story: #4389

**Comment by monika-jaeger** [comment]
I think the details currently on this one should be for ticket #4471. Instead the designers task should be to create comps for the desktop-lg breakpoint at 1200px to illustrate 2 col Flag Cards are >= 1200px 

cc: @andyvanavery31 @welshja @blilianyu

**Comment by monika-jaeger** [comment]
Created a comp with the 1200px desktop-lg breakpoint to illustrate 2-col flag layout at 1200px, and desktop 1024 will be 1-col https://www.figma.com/design/GCOniv8OTyj9OC1udKwo6S/Mini-Landing-Pages?node-id=5719-80379&t=rgv4njGMiMuVc6Og-1

cc: @andyvanavery31 @welshja @blilianyu

**Comment by andyvanavery31** [comment]
@monika-jaeger I updated the ticket and fixed the copy/paste error and reviewed the comp. Could you and/or @blilianyu please update the review and update the following?

General:
-	Can we reverse the order so mobile comes first (on the left)? This should help us focus on mobile-first development
-	When a card grows in height to match the height of the one with more text, I don’t think the bottom padding token should be shown. It seems useless/confusing because there is so much more space below the token and it’s not measuring anything. See Widescreen row 1 left card, and Desktop row 1 left card.

Widescreen:
-	Please make the width of the widescreen comp page be 1400px instead of 1600px
-	Can you make the bottom padding token below the description text touch the bottom of the card? In the first row on the right card, the combined height of the top padding, title, top of description padding, description, and below description padding = 156px, but the flag card is 176px tall. Similar behavior happens in the second row on the left card
-	Can you add the horizontal space token between the two columns (32px)?

Desktop Lg
-	Please put the vertical and horizontal spacing tokens between the flag card rows and columns respectively
-	It looks like there is too much whitespace on the left side of the screen (left of the side nav) which is causing everything to be shrunk inside the main content of the page. Can you fix this so the widths of the flag cards and the wrapping of the text is correct? It should look like the screenshot:
 

Desktop
-	In the single column stack, the top and bottom padding doesn’t really help indicate the behavior there. From what we wrote in the requirements, if there is a title and description, the center of that should be center aligned (cards 1-3), and if there is only a title, then the title will be center aligned (card 4). Could we have an indicator of center alignment instead of the paddings that don’t touch a boundary?
-	The “Cancer Types” title only card (card 4) does not look center aligned due to the empty description box

Tablet Lg
-	Same points as Desktop behavior
-	Can the images be added to these? It looks like something changes to the images on the cards when they go from having images to having the placeholder image at this breakpoint

Tablet
-	Same notes as Desktop and Tablet Lg
-	In card 2, the title and text are taller (168px) than the image (160px), but the image should remain top left aligned instead of centered

Mobile Lg
-	On card 4, the Title is not center aligned, it has a 20px space above and the description box below, which is 24px, and it should indicate the 20px bottom token

Mobile
-	Same as Mobile Lg
-	Please add the left side padding to card 4, or remove them everywhere that they are redundant with an indicator of repetition

**Comment by monika-jaeger** [comment]
@andyvanavery31 below are updates to the comps and a few notes. Let me know if we want to discuss the general comments as a group. cc: @blilianyu 

### General

_Can we reverse the order so mobile comes first (on the left)? This should help us focus on mobile-first development._ 
- We have displayed comps and components largest breakpoint to smallest, as that is what's best practices with design kits, but if displaying both our comps and components smallest to largest helps the team think with a mobile first approach we can do so.

_When a card grows in height to match the height of the one with more text, I don’t think the bottom padding token should be shown. It seems useless/confusing because there is so much more space below the token and it’s not measuring anything. See Widescreen row 1 left card, and Desktop row 1 left card._
- Done

### Widescreen
_Please make the width of the widescreen comp page be 1400px instead of 1600px_
- We have built out the widescreen breakpoint on 1600 to account for the hero banner image size, so all our grid spacing for comps fits 1600 for our design kit. I would recommend we leave all widescreen comps at that size, but if we want to move back to 1400, let's discuss our comps overall. 

_Can you make the bottom padding token below the description text touch the bottom of the card? In the first row on the right card, the combined height of the top padding, title, top of description padding, description, and below description padding = 156px, but the flag card is 176px tall. Similar behavior happens in the second row on the left card
Can you add the horizontal space token between the two columns (32px)?_ 
- Done

### Desktop Lg
_Please put the vertical and horizontal spacing tokens between the flag card rows and columns respectively_
- Done 

_It looks like there is too much whitespace on the left side of the screen (left of the side nav) which is causing everything to be shrunk inside the main content of the page. Can you fix this so the widths of the flag cards and the wrapping of the text is correct? It should look like the screenshot:_
- Good catch. Adjusted the gutter size on the left of the side nav, which gave the main content on the page more room. 

### Desktop
_In the single column stack, the top and bottom padding doesn’t really help indicate the behavior there. From what we wrote in the requirements, if there is a title and description, the center of that should be center aligned (cards 1-3), and if there is only a title, then the title will be center aligned (card 4). Could we have an indicator of center alignment instead of the paddings that don’t touch a boundary?_
- I hid the spacers for top/bottom of cards when center aligned. In dev mode, the devs should see for layout: 
justify-content: center;
align-items: center;

_The “Cancer Types” title only card (card 4) does not look center aligned due to the empty description box_
- Fixed, there was a spacer that was not hidden which caused it to not be center aligned. 

### Tablet Lg
_Same points as Desktop behavior_
- Done

_Can the images be added to these? It looks like something changes to the images on the cards when they go from having images to having the placeholder image at this breakpoint_
- Done

### Tablet
_Same notes as Desktop and Tablet Lg_
- Done

_In card 2, the title and text are taller (168px) than the image (160px), but the image should remain top left aligned instead of centered_
- Done

### Mobile Lg
_On card 4, the Title is not center aligned, it has a 20px space above and the description box below, which is 24px, and it should indicate the 20px bottom token_
- Done. The left spacer is hidden on this card since it's taller than the card height and was causing issues. 

### Mobile
_Same as Mobile Lg
Please add the left side padding to card 4, or remove them everywhere that they are redundant with an indicator of repetition_
- Same as Mobile Lg
