### ISSUE TITLE
YAML Demo Content for PDQ Cancer Info Summaries

### ISSUE THREAD

**Issue by lburack** [NCIOCPL/cgov-digital-platform#651]
This ticket is to create the demo .yaml content for a "good sampling" of PDQ content. This should include:
* all the different summary types (by editorial board)
* patient vs health professional summaries
* English and Spanish 
* summaries with tables
* summaries with images
* other one-offs you can think of (can consult with Volker)

**Comment by bkline** [comment]
I have a script which generates the sample YAML for 30 nodes, using a selection determined in consultation with @blairlearn and @venglisch:

```python
    SUMMARIES = {
        # Summary Type:
        "Adult Treatment": {
            # Topic: [HP English, Spanish], [Patient English, Spanish]
            "Breast": [[62787, 256668], [62955, 256762]],
            "Gastric": [[62911, 256670], [271446, 256764]],
            "Merkel Cell": [[62884, 256759], [441548, 470863]],
        },
        "Ped Treatment": {
            "Brain Stem Glioma": [[62761, 256675], [62962, 600419]],
            "Retinoblastoma": [[62846, 256693], [258033, 448617]],
        },
        "Genetics": {
            "Breast and Gynecologic": [[62855, None]],
            "Prostate": [[299612, None]],
        },
        "Integrative, alternative, and complementary therapies": {
            "High-Dose Vitamin C": [[742114, 773659], [742253, 773656]],
            "Mistletoe Extracts": [[269596, 778124], [449678, 778123]],
            "Bovine Shark Cartilage": [[62974, 789591], [446198, 789592]],
        },
        "Prevention": {
            "Breast": [[62779, 744468], [257994, 744469]],
            "Lung": [[62824, 733624], [62825, 729199]],
        },
        "Screening": {
            "Breast": [[62751, 744470], [257995, 744471]],
            "Lung": [[62832, 700433], [258019, 700560]],
        },
        "Supportive": {
            "Fatigue": [[62734, 256627], [62811, 256650]],
            "Pruritus": [[62748, 256645], [62805, 256622]],
        },
    }
```

The YAML file weighs in at around 10MB.

The current version of the script inserts node IDs, because there's a bug in the `yaml_content` module which is unable to populate the `path` field unless a node ID is present.

The script will be rewritten, following up on yesterday's PDQ requirements meeting, to drop the node IDs and the `path` field, replacing them with a new `url` field. That work depends on the definition of the `url` field, and on the creation of a `path_auto` rule to use the new field, as requested by @bryanpizzillo in that meeting; I'm coordinating with @blairlearn on these tasks.

One additional note: I tried writing the script using the contributed python `yaml` module, but either its serialization logic is not compliant with the YAML specification, or the PHP parser is not compliant, or the two packages are using different versions of the spec, because the output of the Python module was rejected by the PHP code as malformed. Rather than wrestle with tracking down and possibly fixing the incompatibility I just rewrote my script to generate my own YAML serialization, which appears to work perfectly (and is more than an order of magnitude faster as a side benefit).
