### ISSUE TITLE
Implement automatic generation of sitemap xml 

### ISSUE THREAD

**Issue by VictoriaSunNIH** [NCIOCPL/cgov-digital-platform#792]
When we implement the automatic generation of sitemap XML, this should generate sitemaps for:
* Cancer.gov
* Each microsite under cancer.gov (nano, nciconnect, mypart, dceg)

**Comment by BrendanBeltzNIH** [comment]
https://www.drupal.org/project/simple_sitemap or https://www.drupal.org/project/xmlsitemap ?

**Comment by bryanpizzillo** [comment]
Simple sitemap looks the way to go between the two.

Some high level requirements (which @VictoriaSunNIH  should have somewhere)
Current sitemap for reference.
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>
https://www.cancer.gov/sitemaps/pageinstructions.xml
</loc>
<lastmod>2019-04-24T10:58:34.1142873-04:00</lastmod>
</sitemap>
<sitemap>
<loc>https://www.cancer.gov/sitemaps/dictionaries.xml</loc>
<lastmod>2019-04-24T10:58:34.1142873-04:00</lastmod>
</sitemap>
<sitemap>
<loc>
https://www.cancer.gov/sitemaps/dynamiclistingpages.xml
</loc>
<lastmod>2019-04-24T10:58:34.1142873-04:00</lastmod>
</sitemap>
<sitemap>
<loc>https://www.cancer.gov/sitemaps/clinicaltrials.xml</loc>
<lastmod>2019-04-24T10:58:34.1142873-04:00</lastmod>
</sitemap>
</sitemapindex>
```
* We have a sitemap index.
* We currently have only 1 autogenerated index. the other two need to be added by hand. So I hope the module allows for adding random links to a sitemap
* Given there are subsites, this may get tricky. Currently `https://www.cancer.gov/sitemaps/pageinstructions.xml`  includes nano, nci-connect, etc. These will have to be added by hand as above. I don't know if an index can point at an index, so that may be an annoying fiddly bit.

So to put a bit of a sandbox around this ticket, probably should be a spike:
1. Add the module (i hope it supports our requirements)
2. Add the sitemap index (I hope they do that by default)
3. Add all the nodes, infographic and video media items to a sitemap in the index. (I think we got rid of indexing files -- right @VictoriaSunNIH )
4. Add hardcoded sitemaps for the other three site maps (e.g. `https://www.cancer.gov/sitemaps/dictionaries.xml`)
5. Profit?

**Comment by VictoriaSunNIH** [comment]
@bryanpizzillo - actually, according to our requirements, pages and files were both included in the Sitemap.  Here were our requirements:
- XML sitemap should include URLs for pages and files.
- Do not need to include date.
- Set frequency to “Weekly”
- Use the following priority values (by content type):
  * Home and Landing pages = 1.0
  * Cancer Type Home Pages = 1.0
  * PDQ Summaries = 1.0
  * Articles = 1.0
  * Cancer Research List Page = 1.0
  * Everything else can get the default priority of 0.5.
