### ISSUE TITLE
Allow custom ~/.bashrc to be injected into docker containers (per local user)

### ISSUE THREAD

**Issue by bgnih** [NCIOCPL/cgov-digital-platform#96]
Allow devs to add their own custom code to be injected into the docker containers' ~/.bashrc file to store aliases, function and other customizations.   Customizations should be local to the computer and not be committed to repo.

Use a mounted file that `source`'s the customizations (if they exist) from `/root/.bashrc`

**Comment by blairlearn** [comment]
This can be accomplished via a bind mount in the `docker-compose.override.yml` file.

E.g. If the custom .bashrc file is stored in `~/my-custom-docker-bash.sh`, then the `docker-compose.override.yml` file would look something like this:

```
version: "3.7"

services:

  web:
    volumes:
      - ~/my-custom-docker-bash:/root/.bashrc
```

Note that in order to be a bind mount instead of a named (not locally mapped) volume, the left portion of the volume specification **must** begin with one of `~` (tilde), `.` (period), or `/` (forward-slash).
