### ISSUE TITLE
Create Blog Series templates

### ISSUE THREAD

**Issue by daquinohd** [NCIOCPL/cgov-digital-platform#975]
## Description 
Add twig templates for the cgov_blog_series content type. Currently, only the Blog Post list view shows up on Blog Series pages; the template should display the Banner Image, Intro Text, and Featured Posts. 

This ticket just involves getting the field data onto the page - the look and feel components will be handled in #785.

**Comment by bgnih** [comment]
@bryanpizzillo @daquinohd @lburack: Here's my standard bajillion questions/issues for this ticket:
1. [Requirements](https://github.com/NCIOCPL/cgov-digital-platform/wiki/Content-Type-Blog-Series) are missing fields that are present in current content type (eg: Intro Text, Body).  Which is correct?
1. On the edit form, `Intro Text` and `Body` are hidden.  Is this intentional or should I move one or both into the edit form?
1. The `200_blog-series.content.yml` content has incorrect and missing data.  Shall I fix this as part of this ticket?
    1. Remove duplicate field names 
    1. Add `field_intro_text`
    1. Add `field_banner_image`
    1. Add `field_page_description`
    1. Do we need Spanish content in this?
    1. `Site Section / Pretty URL` combinations need to be updated.
        1. `Cancer Currents Blog` PrettyURL needs path removed (take out `/news-events/` leaving `cancer-currents-blog`
        1. `RAS Dialogue Blog.Pretty URL` is `research/key-initiatives/ras/ras-central/blog`, but paths aren't allowed.  Remove path and set Site Section to `RAS Central`
1. The Spanish translation of `Cancer Currents Blog` is a separate node.  Should it be a translation of the English node instead?  Shall I correct it as part of this ticket?
1. Should I add the `Public Use` field to the template while I'm in here, and move it out of the Full display mode?

**Comment by daquinohd** [comment]
@bgnih: 

> 1. Requirements are missing fields that are present in current content type (eg: Intro Text, Body). Which is correct?
> 2. On the edit form, Intro Text and Body are hidden. Is this intentional or should I move one or both into the edit form?

Intro Text and Body should should not be part of the content type and can be removed completely from the Blog Series. 

> 5. The Spanish translation of Cancer Currents Blog is a separate node. Should it be a translation of the English node instead? Shall I correct it as part of this ticket?

Yes, if it's not too much trouble. 

> 6. Should I add the Public Use field to the template while I'm in here, and move it out of the Full display mode?

Is that the same implementation you're using on the other content types? If so, go ahead and do that.

**Comment by bgnih** [comment]
Assigning to @daquinohd for review/merge/signoff.
